global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'myapp'
    scrape_interval: 1s
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # or container-name:8090
  # - job_name: 'node'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  - job_name: 'windows'
    static_configs:
      - targets: ['host.docker.internal:9182']